/**
 * Offline tests for the per-gate alpha telemetry + the suite cascade contract.
 * No DB, no key, no LLM — the measured slice is read from the committed offline
 * replay and the counters are pure/in-memory.
 * Run: npx tsx --test lib/quality-gates/cascade-telemetry.test.ts
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  GATE_REGISTRY,
  GateCounter,
  buildGateDecision,
  buildMeasuredSentence,
  getCascadeReplaySlice,
  summarizeRequestCascade,
  type GateId,
  type CascadeSlice,
} from './cascade-telemetry';

const ALL_GATES: GateId[] = ['ood-gate', 'data-density', 'info-gain', 'satisficing'];

test('GATE_REGISTRY: every gate carries a regime + residual locus label', () => {
  for (const id of ALL_GATES) {
    const meta = GATE_REGISTRY[id];
    assert.equal(meta.id, id);
    assert.ok(['model-free', 'model-based-residual', 'hybrid'].includes(meta.regime));
    assert.ok(['turn', 'claim', 'action', 'step', 'chunk'].includes(meta.locus));
    assert.ok(meta.cheapTier.length > 0 && meta.expensiveTier.length > 0);
  }
});

test('GATE_REGISTRY: regimes are honest (deterministic gates are model-free)', () => {
  // The OOD gate is a deterministic threshold over geometry => model-free.
  assert.equal(GATE_REGISTRY['ood-gate'].regime, 'model-free');
  assert.equal(GATE_REGISTRY['data-density'].regime, 'model-free');
  assert.equal(GATE_REGISTRY['info-gain'].regime, 'model-free');
  // Satisficing stops on the LLM-judge score => its residual consumes a model.
  assert.equal(GATE_REGISTRY['satisficing'].regime, 'model-based-residual');
  // info-gain's residual lives at the retrieval STEP; the others at the turn.
  assert.equal(GATE_REGISTRY['info-gain'].locus, 'step');
  assert.equal(GATE_REGISTRY['ood-gate'].locus, 'turn');
});

test('losslessMeasured: only the OOD->LLM boundary has committed dual-tier data', () => {
  // Honest: we do NOT fabricate a lossless count for gates without a replay
  // corpus that ran both the skip and no-skip variants through the judge.
  assert.equal(GATE_REGISTRY['ood-gate'].losslessMeasured, true);
  assert.equal(GATE_REGISTRY['data-density'].losslessMeasured, false);
  assert.equal(GATE_REGISTRY['info-gain'].losslessMeasured, false);
  assert.equal(GATE_REGISTRY['satisficing'].losslessMeasured, false);
});

test('cascade slice: emits the contract triple and matches the committed replay', () => {
  const slice = getCascadeReplaySlice();
  // The contract shape: alpha / disagreementRate / losslessViolations present.
  for (const key of ['alpha', 'disagreementRate', 'losslessViolations'] as const) {
    assert.ok(key in slice, `missing contract field ${key}`);
  }
  assert.equal(slice.boundary, 'ood-gate->llm-generation');
  assert.equal(slice.n, 24);
  // Committed measured values (regenerated by scripts/calibrate-ood-gate.ts).
  assert.ok(Math.abs(slice.alpha - 0.083333) < 1e-6);
  assert.ok(Math.abs(slice.expensiveShare - 0.916667) < 1e-6);
  assert.equal(slice.disagreementRate, 0);
  assert.equal(slice.losslessViolations, 0);
});

test('cascade slice: alpha + expensiveShare partition the queries', () => {
  const slice = getCascadeReplaySlice();
  assert.ok(Math.abs(slice.alpha + slice.expensiveShare - 1) < 1e-6);
  assert.ok(slice.alpha >= 0 && slice.alpha <= 1);
  assert.ok(Number.isInteger(slice.losslessViolations) && slice.losslessViolations >= 0);
});

test('buildMeasuredSentence: recruiter-legible and faithful to the slice', () => {
  const sentence = buildMeasuredSentence();
  assert.ok(sentence.length > 80);
  // Carries the measured numbers, not vibes.
  assert.match(sentence, /24-query/);
  assert.match(sentence, /8\.3%/); // alpha
  assert.match(sentence, /91\.7%/); // expensiveShare
  assert.match(sentence, /0 lossless violations/);
  assert.match(sentence, /before any LLM call/);
  // A custom slice flows through (the README sentence is derived, not hardcoded).
  const custom: CascadeSlice = {
    boundary: 'b',
    alpha: 0.25,
    expensiveShare: 0.75,
    disagreementRate: 0.1,
    losslessViolations: 3,
    n: 40,
  };
  const s2 = buildMeasuredSentence(custom);
  assert.match(s2, /40-query/);
  assert.match(s2, /25\.0%/);
  assert.match(s2, /3 lossless violations/);
});

test('buildGateDecision: stamps regime + locus from the registry', () => {
  const d = buildGateDecision('satisficing', true);
  assert.equal(d.gate, 'satisficing');
  assert.equal(d.regime, GATE_REGISTRY['satisficing'].regime);
  assert.equal(d.locus, GATE_REGISTRY['satisficing'].locus);
  assert.equal(d.skippedExpensiveStep, true);
  // null => the gate did not apply this turn (honest tri-state).
  assert.equal(buildGateDecision('info-gain', null).skippedExpensiveStep, null);
});

test('GateCounter: accumulates skip-vs-escalate per gate', () => {
  const c = new GateCounter();
  assert.deepEqual(c.acceptanceRate('ood-gate'), { runs: 0, skips: 0, rate: null });

  c.record('ood-gate', true); // cheap tier resolved (skipped the LLM)
  c.record('ood-gate', false); // escalated to the LLM
  c.record('ood-gate', false);
  const r = c.acceptanceRate('ood-gate');
  assert.equal(r.runs, 3);
  assert.equal(r.skips, 1);
  assert.ok(Math.abs((r.rate ?? -1) - 1 / 3) < 1e-9);

  c.record('satisficing', true);
  const snap = c.snapshot();
  // Only gates that have been recorded appear.
  assert.deepEqual(Object.keys(snap).sort(), ['ood-gate', 'satisficing']);
  assert.equal(snap['satisficing'].rate, 1);
  assert.ok(!('info-gain' in snap));
});

test('summarizeRequestCascade: bundles per-turn decisions with the measured slice', () => {
  const decisions = [
    buildGateDecision('ood-gate', false),
    buildGateDecision('info-gain', null),
    buildGateDecision('data-density', true),
    buildGateDecision('satisficing', true),
  ];
  const payload = summarizeRequestCascade(decisions);
  assert.equal(payload.gates.length, 4);
  assert.deepEqual(payload.measured, getCascadeReplaySlice());
  // Every surfaced gate carries its regime + locus (for the UI / audit).
  for (const g of payload.gates) {
    assert.ok(g.regime && g.locus);
  }
});
