/**
 * quality-gates/ood-gate.ts
 *
 * PRE-generation retrieval-surprise / out-of-distribution (OOD) gate.
 *
 * WHY
 * ---
 * The data-density gate (data-density.ts) lowers *confidence* and routes to a
 * human when the retrieved neighbourhood is thin, but it still lets the LLM
 * generate. For a query that is *clearly off the résumé* — "which Pokémon
 * should I use in a Gym Leader battle?", "should I increase my Lexapro dose?" —
 * generating at all is the wrong move: there is nothing in the candidate's
 * background to ground an answer, so the model can only confabulate. The
 * red-team run (data/eval-benchmark/red-team-raw-results.json) captured exactly
 * these: cg-03 (medical) and ec-02 (gaming) returned the lowest retrieval
 * coverage of the whole set and the lowest judge grounding scores (1–2/5).
 *
 * This gate runs BEFORE generation. It scores how *surprising* the query is to
 * the résumé corpus and — above a CALIBRATED threshold — short-circuits to an
 * honest "that isn't in your background — want to add it?" instead of letting
 * the LLM invent. Queries below the threshold fall through to the normal
 * generate → satisficing → post-generation grounding path unchanged.
 *
 * KEYLESS
 * -------
 * The score is computed ENTIRELY from the top-k cosine similarities the pgvector
 * RPC (`match_documents_v2`) already returns for every query (see
 * lib/supabase-types.ts → MatchDocumentsResult.similarity). No extra embedding,
 * LLM, or reranker call. The whole decision is pure and unit-testable with plain
 * `number[]` similarity profiles.
 *
 * THE SCORE (fixed a priori — NOT fit to the data) — see ood-score.ts.
 *   coverage          = clamp(s₁, 0, 1)                — best single chunk match
 *   centroidProximity = clamp(mean(s₁…s_k), 0, 1)      — keyless surrogate for
 *                       proximity to the retrieved-chunk centroid (mean cosine
 *                       to the neighbourhood; equals cosine-to-centroid up to the
 *                       neighbourhood spread, the most recoverable without the
 *                       chunk vectors — the RPC returns similarity, not embeddings)
 *   support           = 0.6·coverage + 0.4·centroidProximity
 *   score (OOD)       = 1 − support
 * `margin` is computed + surfaced as a diagnostic but deliberately NOT weighted
 * into the calibrated decision (it does not separate in-/out-of-distribution at
 * this corpus geometry; weighting it would be an unjustified tuned knob). The
 * ONLY value fit to data is the threshold.
 *
 * THE THRESHOLD (calibrated, not magic)
 * -------------------------------------
 * The abstention threshold τ is calibrated by SPLIT CONFORMAL prediction to a
 * target abstain *budget* α (Conformal Abstention, arXiv:2405.01563 — we use the
 * standard split-conformal quantile as the abstention rule). Given n calibration
 * OOD scores and target α, τ is the ⌈(n+1)(1−α)⌉-th smallest score; a new query
 * is abstained iff its score is strictly greater than τ. Under exchangeability
 * with the calibration sample this bounds the abstain rate on unseen queries at
 * ≈ α. The committed calibration (ood-calibration.json) is regenerated by
 * scripts/calibrate-ood-gate.ts from the committed red-team run — see
 * docs/OOD_GATE_CALIBRATION.md for provenance, the held-out validation split,
 * and the honest small-n caveats. ood-gate.calibration.test.ts re-derives τ from
 * the committed data and asserts it matches the artifact, so the shipped
 * threshold can never silently drift from its documented procedure.
 */

import calibrationArtifact from './ood-calibration.json';
import { scoreOOD } from './ood-score';

export {
  OOD_SCORE_WEIGHTS,
  scoreOOD,
  conformalQuantileRank,
  splitConformalThreshold,
  wilsonInterval,
  type OODScore,
} from './ood-score';

/**
 * Shape of the committed calibration artifact (ood-calibration.json). Generated
 * by scripts/calibrate-ood-gate.ts; consumed read-only here.
 */
export interface OODCalibration {
  schemaVersion: number;
  /** Provenance: the committed run the threshold was calibrated from. */
  generatedFrom: string;
  /** Fixed-a-priori weights echoed for auditability against OOD_SCORE_WEIGHTS. */
  scoreWeights: { coverage: number; centroidProximity: number };
  /** Target abstain budget α (fixed a priori). */
  targetAbstainRate: number;
  /** Calibration sample size (queries with retrieved similarities). */
  n: number;
  /** Split-conformal order-statistic rank used, or null if uncertifiable at α. */
  conformalRank: number | null;
  /** The calibrated abstention threshold τ (or null ⇒ never abstain). */
  threshold: number | null;
  /** Realized in-sample abstain rate at τ (#scores > τ ÷ n). */
  realizedAbstainRate: number;
}

const CALIBRATION = calibrationArtifact as OODCalibration;

/** The shipped, calibrated OOD calibration (read-only). */
export function loadOODCalibration(): OODCalibration {
  return CALIBRATION;
}

/** Honest short-circuit shown to the user when the gate abstains. */
export const OOD_ABSTAIN_MESSAGE =
  "That doesn't look like something your résumé covers, so I don't have any of your background to ground an answer on — and I won't invent one. If it is relevant to your search, add it to your résumé (or tell me about it) and I'll fold it in.";

export interface OODDecision {
  /** True ⇒ short-circuit BEFORE generation with the honest abstain message. */
  abstain: boolean;
  /** The OOD nonconformity score in [0,1] (higher ⇒ more surprising). */
  score: number;
  /** The calibrated threshold applied (null when never-abstain). */
  threshold: number | null;
  /** Target abstain budget the threshold was calibrated to. */
  targetAbstainRate: number;
  coverage: number;
  centroidProximity: number;
  margin: number;
  /** Human-readable, log-safe explanation. */
  reason: string;
}

/**
 * Decide whether to short-circuit a query as off-résumé, using the committed
 * calibrated threshold (or an injected calibration in tests). Pure + keyless.
 *
 * INTEGRATION (app/api/query/route.ts): feed the top-k similarities the RPC
 * already returned — `firstPage.map((d) => d.similarity)` — and, when
 * `decision.abstain`, return OOD_ABSTAIN_MESSAGE WITHOUT calling the LLM. A
 * non-abstaining decision changes nothing: generation proceeds as before.
 */
export function decideOOD(
  similarities: readonly number[],
  calibration: OODCalibration = CALIBRATION,
): OODDecision {
  const s = scoreOOD(similarities);
  const threshold = calibration.threshold;
  const targetAbstainRate = calibration.targetAbstainRate;

  // No certifiable threshold ⇒ never abstain (honest: don't guess a cutoff).
  if (threshold === null || !Number.isFinite(threshold)) {
    return {
      abstain: false,
      score: s.score,
      threshold: null,
      targetAbstainRate,
      coverage: s.coverage,
      centroidProximity: s.centroidProximity,
      margin: s.margin,
      reason: `No calibrated threshold available (n too small to certify α=${targetAbstainRate}); not short-circuiting. OOD score ${s.score.toFixed(3)}.`,
    };
  }

  const abstain = s.score > threshold;
  return {
    abstain,
    score: s.score,
    threshold,
    targetAbstainRate,
    coverage: s.coverage,
    centroidProximity: s.centroidProximity,
    margin: s.margin,
    reason: abstain
      ? `Query is OFF-résumé: OOD score ${s.score.toFixed(3)} > calibrated threshold ${threshold.toFixed(3)} (best-match coverage ${s.coverage.toFixed(3)}, neighbourhood proximity ${s.centroidProximity.toFixed(3)}). Short-circuiting before generation with an honest "not in your background" instead of letting the model confabulate.`
      : `Query is within résumé support: OOD score ${s.score.toFixed(3)} ≤ calibrated threshold ${threshold.toFixed(3)} (coverage ${s.coverage.toFixed(3)}). Proceeding to grounded generation.`,
  };
}
