/**
 * Unit tests for upload-pipeline.
 *
 * No OpenAI, no Supabase, no network: embedding and insertion are injected
 * fakes. PDF extraction runs the REAL pdf-parse dependency against fixtures
 * generated by scripts/lib/minimal-pdf.mjs — the same generator the live
 * verifier (scripts/verify-live.mjs) uploads, so these tests also prove the
 * verifier's probe file is readable by the app's own extractor.
 *
 * Run: npx tsx --test lib/upload-pipeline.test.ts
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { buildMinimalPdf } from '../scripts/lib/minimal-pdf.mjs';
import {
  validateUploadForm,
  extractPdfText,
  splitResumeText,
  runUploadIngestion,
  type UploadIngestionDeps,
} from './upload-pipeline';
import type { DocumentInsert } from './supabase-types';

// ---------------------------------------------------------------------------
// validateUploadForm — the multipart boundary. Every rejection here used to
// surface as a 500 TypeError deep in the handler; now it is a designed 400.
// ---------------------------------------------------------------------------

test('missing file -> invalid with the legacy message', () => {
  const v = validateUploadForm(null, 'user-1');
  assert.equal(v.ok, false);
  if (!v.ok) assert.equal(v.error, 'Missing file or userId');
});

test('missing userId -> invalid with the legacy message', () => {
  const file = new File(['%PDF-'], 'resume.pdf', { type: 'application/pdf' });
  const v = validateUploadForm(file, null);
  assert.equal(v.ok, false);
  if (!v.ok) assert.equal(v.error, 'Missing file or userId');
});

test('file posted as a text field (string) -> invalid, not a TypeError', () => {
  // FormData.get() returns a string when the client sends a plain field named
  // "file". The old handler cast it to File and crashed on .arrayBuffer().
  const v = validateUploadForm('resume contents as text', 'user-1');
  assert.equal(v.ok, false);
  if (!v.ok) assert.match(v.error, /file/i);
});

test('userId posted as a file part -> invalid', () => {
  const file = new File(['%PDF-'], 'resume.pdf', { type: 'application/pdf' });
  const bogusUserId = new File(['u'], 'userId.txt');
  const v = validateUploadForm(file, bogusUserId);
  assert.equal(v.ok, false);
  if (!v.ok) assert.match(v.error, /userId/i);
});

test('whitespace-only userId -> invalid', () => {
  const file = new File(['%PDF-'], 'resume.pdf', { type: 'application/pdf' });
  const v = validateUploadForm(file, '   ');
  assert.equal(v.ok, false);
  if (!v.ok) assert.match(v.error, /userId/i);
});

test('valid file + userId -> ok, values passed through', () => {
  const file = new File(['%PDF-'], 'resume.pdf', { type: 'application/pdf' });
  const v = validateUploadForm(file, 'user-1');
  assert.equal(v.ok, true);
  if (v.ok) {
    assert.equal(v.file, file);
    assert.equal(v.userId, 'user-1');
  }
});

// ---------------------------------------------------------------------------
// extractPdfText — REAL pdf-parse. Locks the fix for the /api/upload 500:
// pdf-parse's bundled pdf.js misreads Node Buffer views (it dereferences
// bytes.buffer with absolute offsets, so pooled/view Buffers parse garbage
// from the surrounding pool). The extractor must normalize its input so a
// valid PDF parses no matter which Buffer flavor the route hands it.
// ---------------------------------------------------------------------------

test('extracts text from a valid PDF handed as a pool-backed Node Buffer', async () => {
  // Buffer.from(Uint8Array) copies into Node's shared buffer pool — the
  // Buffer flavor that made pdf-parse fail with "bad XRef entry" on a
  // perfectly valid document (reproduced against pdf-parse@1.1.4).
  const pooled = Buffer.from(buildMinimalPdf('UPLOAD SENTINEL 4821\nSecond line of the resume.'));
  const text = await extractPdfText(pooled);
  assert.match(text, /UPLOAD SENTINEL 4821/);
  assert.match(text, /Second line of the resume\./);
});

test('extracts text from a valid PDF handed as a plain Uint8Array', async () => {
  const bytes = new Uint8Array(buildMinimalPdf('PLAIN ARRAY SENTINEL'));
  const text = await extractPdfText(bytes);
  assert.match(text, /PLAIN ARRAY SENTINEL/);
});

test('rejects bytes that are not a PDF', async () => {
  await assert.rejects(() => extractPdfText(Buffer.from('definitely not a pdf')));
});

// ---------------------------------------------------------------------------
// splitResumeText — deterministic chunking (real splitter, no network).
// ---------------------------------------------------------------------------

test('short text -> a single chunk containing the text', async () => {
  const chunks = await splitResumeText('A short resume.');
  assert.equal(chunks.length, 1);
  assert.equal(chunks[0], 'A short resume.');
});

test('long text -> multiple chunks, each within the 1000-char budget', async () => {
  const long = Array.from({ length: 400 }, (_, i) => `line ${i} of experience.`).join('\n');
  const chunks = await splitResumeText(long);
  assert.ok(chunks.length > 1, `expected >1 chunks, got ${chunks.length}`);
  for (const chunk of chunks) {
    assert.ok(chunk.length <= 1000, `chunk exceeds budget: ${chunk.length}`);
  }
});

// ---------------------------------------------------------------------------
// runUploadIngestion — orchestration with injected deps.
// ---------------------------------------------------------------------------

function fakeDeps(overrides: Partial<UploadIngestionDeps> = {}): {
  deps: UploadIngestionDeps;
  embedded: string[][];
  inserted: DocumentInsert[][];
} {
  const embedded: string[][] = [];
  const inserted: DocumentInsert[][] = [];
  const deps: UploadIngestionDeps = {
    extractPdfText: async () => 'Led the ML platform team. Shipped a RAG system to production.',
    splitText: async (text) => [text],
    embedChunks: async (chunks) => {
      embedded.push(chunks);
      return chunks.map((_, i) => [i, i + 0.5]);
    },
    insertDocuments: async (rows) => {
      inserted.push(rows);
      return { error: null };
    },
    newResumeId: () => 'resume-fixed-id',
    ...overrides,
  };
  return { deps, embedded, inserted };
}

const INPUT = {
  buffer: Buffer.from('%PDF- placeholder bytes'),
  fileName: 'resume.pdf',
  userId: 'user-1',
};

test('happy path -> ok with resumeId and chunk count; rows carry content, embedding, metadata', async () => {
  const { deps, inserted } = fakeDeps({
    splitText: async () => ['chunk one', 'chunk two'],
  });
  const result = await runUploadIngestion(INPUT, deps);
  assert.deepEqual(result, { status: 'ok', resumeId: 'resume-fixed-id', chunks: 2 });
  assert.equal(inserted.length, 1);
  const rows = inserted[0];
  assert.equal(rows.length, 2);
  assert.equal(rows[0].content, 'chunk one');
  assert.deepEqual(rows[0].embedding, [0, 0.5]);
  assert.deepEqual(rows[1].embedding, [1, 1.5]);
  assert.deepEqual(rows[0].metadata, {
    source: 'resume.pdf',
    user_id: 'user-1',
    resume_id: 'resume-fixed-id',
  });
});

test('a real generated PDF flows through the real extractor and splitter to ok', async () => {
  const { deps } = fakeDeps();
  const result = await runUploadIngestion(
    {
      buffer: Buffer.from(buildMinimalPdf('Full-stack engineer. Built evaluation harnesses.')),
      fileName: 'real.pdf',
      userId: 'user-2',
    },
    { ...deps, extractPdfText, splitText: splitResumeText },
  );
  assert.equal(result.status, 'ok');
  if (result.status === 'ok') assert.ok(result.chunks >= 1);
});

test('unparseable PDF -> unparseable-pdf, and no embedding call is spent', async () => {
  const { deps, embedded } = fakeDeps({
    extractPdfText: async () => {
      throw new Error('bad XRef entry');
    },
  });
  const result = await runUploadIngestion(INPUT, deps);
  assert.deepEqual(result, { status: 'unparseable-pdf' });
  assert.equal(embedded.length, 0);
});

test('PDF with no extractable text -> empty-pdf, and no embedding call is spent', async () => {
  const { deps, embedded } = fakeDeps({ extractPdfText: async () => '  \n ' });
  const result = await runUploadIngestion(INPUT, deps);
  assert.deepEqual(result, { status: 'empty-pdf' });
  assert.equal(embedded.length, 0);
});

test('insert failure -> backend-error carrying the message for the server log', async () => {
  const { deps } = fakeDeps({
    insertDocuments: async () => ({ error: { message: 'connection refused' } }),
  });
  const result = await runUploadIngestion(INPUT, deps);
  assert.deepEqual(result, { status: 'backend-error', message: 'connection refused' });
});

test('embedding failure propagates (a generic upstream fault, not a designed state)', async () => {
  const { deps } = fakeDeps({
    embedChunks: async () => {
      throw new Error('openai unreachable');
    },
  });
  await assert.rejects(() => runUploadIngestion(INPUT, deps), /openai unreachable/);
});

test('resumeId defaults to a fresh UUID when no generator is injected', async () => {
  const { deps } = fakeDeps();
  delete (deps as { newResumeId?: unknown }).newResumeId;
  const result = await runUploadIngestion(INPUT, deps);
  assert.equal(result.status, 'ok');
  if (result.status === 'ok') {
    assert.match(result.resumeId, /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/);
  }
});
