import { synthesizeCareerReport } from "@/lib/agents/synthesizer/node";

export async function generateReport(data: any) {
  const report = synthesizeCareerReport(data);

  const markdown = `
# AI Career Coach — Full Report for Theo Bermudez

**Target:** ${report.targetCompany} APM Role  
**Generated:** ${new Date(report.generatedAt).toLocaleDateString()}

## Resume Analysis
${report.resumeAnalysis.summary ?? ""}

## Gap Analysis (Fit Score: ${report.gapAnalysis.roleFitScore}/100)
${report.gapAnalysis.missingTechnicalSkills
  .map((s: string) => `- ${s}`)
  .join("\n") || "None"}

## Personalized Cover Letter
${report.coverLetter.letter}

## Interview Preparation (10 Questions)
${report.interviewPrep.behavioral
  .map(
    (q: any) =>
      `**Q:** ${q.question}\n**A:** ${q.answer}`
  )
  .join("\n\n")}

## 6-Month Strategy Plan
${report.strategyPlan.monthlyBreakdown
  .map(
    (m: any) =>
      `### Month ${m.month}: ${m.focus}\n${m.keyMilestones
        .map((km: string) => `- ${km}`)
        .join("\n")}`
  )
  .join("\n\n")}

**This report was 100% generated by Theo's AI Career Coach — built with LangGraph, Supabase RAG, and Cursor.**
`;

  return {
    markdown,
    // We return markdown, so use .md extension; user can print/export to PDF.
    filename: `Theo_Bermudez_${report.targetCompany}_Career_Report.md`,
  };
}


